name: build

on:
  pull_request:
    paths:
      - 'build.sh'
      - '.github/workflows/build.yml'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install inkscape
        run: |
          sudo add-apt-repository -y ppa:inkscape.dev/stable
          sudo apt-get -y update
          sudo apt-get install -y inkscape

      - name: build-dot
        run: |
          STYLE=dot ./build.sh

      - name: build-number
        run: |
          STYLE=number ./build.sh

